### ISSUE TITLE
Failing tests are broken

### ISSUE THREAD

**Issue by pesekon2** [storm-fsv-cvut/smoderp2d#226]
When the consistency tests find some inconsistency, they don't report it but crash in errors instead (see the message below). 

I see multiple issues:
- [ ] `gdal` is not present in GH actions (and I would like to avoid having it there as there would be no use)
- [ ] `matplotlib` is not present in GH actions (and I would like to avoid having it there as there would be no use)
- [ ] Even if I run it locally with the extra dependencies installed, I get the error reported below. No differences reported in GH actions. The error was introduced in e00a34a. 

```
ERROR 1: Ungridded dataset: At line 2, Failed to detect grid layout.

tests/test_cmd.py:21 (TestCmd.test_001_roff)
self = <test_cmd.TestCmd object at 0x7f7479297f50>

    def test_001_roff(self):
>       PerformTest(Runner).run_roff(
            self.config_file
        )

tests/test_cmd.py:23: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/test_utils.py:318: in run_roff
    assert are_dir_trees_equal(
tests/test_utils.py:124: in are_dir_trees_equal
    _print_diff_files(dirs_cmp)
tests/test_utils.py:99: in _print_diff_files
    _read_gdal_array(os.path.join(dcmp.right, name)),
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

filename = '/home/ondrej/workspace/smoderp2d/tests/data/reference/quicktest/mqsur_m3_s.asc'

    def _read_gdal_array(filename):
        from osgeo import gdal
        ds = gdal.Open(filename)
>       array = ds.GetRasterBand(1).ReadAsArray()
E       AttributeError: 'NoneType' object has no attribute 'GetRasterBand'

tests/test_utils.py:60: AttributeError
```
